### ISSUE TITLE
Print "something" if I run the tool in cli mode, but I don't pipe anything

### ISSUE THREAD

**Issue by viktorbenei** [huytd/go-play#15]
I was just playing around, and first I didn't understand why if I run `$ go-play` (no params) it just doesn't do anything.

IMO it could either enter into an interactive mode (where you can type in the input), or at least print a warning that this is not the proper usage :)

**Comment by huytd** [comment]
Yeah. Interactive mode is what I planned at the beginning but stopped because it's... complex to do the interactive editor in command line 😅 

But the issue when no params passed to `go-play`, it do nothing, is a bug. 

May be there are some issue with the `os.Stdin` reader, when there are nothing passed, the program just stay there and wait for `os.Stdin`.

**Comment by viktorbenei** [comment]
I agree, and just wanted to include our solution, if you find it helpful (https://github.com/bitrise-io/envman/blob/c6d4b74261e53ffe973b61e72b144c4e0bb4a56f/cli/cli.go#L24). Essentially the same what @p-v implemented in the commits referenced 👍😉

**Comment by p-v** [comment]
Done 👍
